"""Runtime configuration.

The server is read-only and needs exactly one thing: where the graph lives. The
database is not in git -- it is generated by the ingest pipeline and published as
a release asset with the corpus date.
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path
from typing import Final

PACKAGE_ROOT: Final = Path(__file__).resolve().parent
PROJECT_ROOT: Final = PACKAGE_ROOT.parents[1]

#: Where the graph is looked for when ``CITADOR_DB`` is unset.
DEFAULT_DB_PATH: Final = PROJECT_ROOT / "data" / "citador.db"

SCHEMA_PATH: Final = PACKAGE_ROOT / "store" / "schema.sql"

#: Default page size for the paginated tools.
DEFAULT_LIMIT: Final = 20
MAX_LIMIT: Final = 100


def db_path() -> Path:
    """The graph's location. Override with ``CITADOR_DB``."""
    raw = os.environ.get("CITADOR_DB")
    return Path(raw).expanduser() if raw else DEFAULT_DB_PATH


def configure_logging(level: int | None = None) -> None:
    """Send logs to stderr.

    Not a style preference: the server speaks MCP over stdio, so anything written
    to stdout corrupts the protocol frame. There is no ``print()`` anywhere in
    this package, and there should not be.
    """
    if level is None:
        level = getattr(logging, os.environ.get("CITADOR_LOG_LEVEL", "INFO").upper(), logging.INFO)
    logging.basicConfig(
        level=level,
        stream=sys.stderr,
        format="%(asctime)s %(levelname)-8s %(name)s: %(message)s",
    )
